/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package serverapp;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class ServerWin extends javax.swing.JFrame {

    /**
     * Creates new form ServerWin
     */
    public ServerWin() {
        initComponents();
        try{
            String query="select * from user_master";
       ResultSet rs=res.ConnectionFactory.getInstance().getResultSet(query);
       while(rs.next())
       {
          DefaultTableModel tmodel=(DefaultTableModel)this.tblUsers.getModel();
          Vector<String> rowData=new Vector<String>();
            rowData.add(rs.getString(2));
        rowData.add(rs.getString(4));
        rowData.add( rs.getDate(8).toString());
        if(rs.getInt(7)==1)
         rowData.add("Active");
        else
            rowData.add("InActive");
        tmodel.addRow(rowData);
        tmodel.fireTableDataChanged();
       }
        }catch(Exception ex){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serverpane = new javax.swing.JTabbedPane();
        tabStatus = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtStatus = new javax.swing.JTextArea();
        tabUsers = new javax.swing.JPanel();
        jdisable = new javax.swing.JButton();
        jenable = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        tabReg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLogid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        txtPass = new javax.swing.JPasswordField();
        txtCnfPass = new javax.swing.JPasswordField();
        btnSubmit = new javax.swing.JButton();
        tbarMsg = new javax.swing.JToolBar();
        lblMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        serverpane.setAutoscrolls(true);
        serverpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                serverpaneMouseEntered(evt);
            }
        });

        txtStatus.setColumns(20);
        txtStatus.setRows(5);
        txtStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtStatusMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(txtStatus);

        javax.swing.GroupLayout tabStatusLayout = new javax.swing.GroupLayout(tabStatus);
        tabStatus.setLayout(tabStatusLayout);
        tabStatusLayout.setHorizontalGroup(
            tabStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabStatusLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabStatusLayout.setVerticalGroup(
            tabStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );

        serverpane.addTab("Network Status", tabStatus);

        jdisable.setText("DISABLE");
        jdisable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdisableActionPerformed(evt);
            }
        });

        jenable.setText("ENABLE");

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Login Id", "User Name", "Reg On", "Status"
            }
        ));
        jScrollPane3.setViewportView(tblUsers);

        javax.swing.GroupLayout tabUsersLayout = new javax.swing.GroupLayout(tabUsers);
        tabUsers.setLayout(tabUsersLayout);
        tabUsersLayout.setHorizontalGroup(
            tabUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jdisable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jenable)
                .addContainerGap())
        );
        tabUsersLayout.setVerticalGroup(
            tabUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabUsersLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(tabUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdisable)
                    .addComponent(jenable))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tabUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        serverpane.addTab("Users", tabUsers);

        jLabel1.setText("Enter Login Id *");

        txtLogid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtLogidMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtLogidMouseExited(evt);
            }
        });
        txtLogid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogidActionPerformed(evt);
            }
        });

        jLabel2.setText("Password *");

        jLabel3.setText("Confirm Password *");

        jLabel4.setText("User Name *");

        txtUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtUserNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtUserNameMouseExited(evt);
            }
        });
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        jLabel5.setText("Email Id *");

        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtEmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtEmailMouseExited(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel6.setText("Description");

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        txtDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDescMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtDescMouseExited(evt);
            }
        });
        jScrollPane2.setViewportView(txtDesc);

        txtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPassMouseExited(evt);
            }
        });

        txtCnfPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCnfPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCnfPassMouseExited(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabRegLayout = new javax.swing.GroupLayout(tabReg);
        tabReg.setLayout(tabRegLayout);
        tabRegLayout.setHorizontalGroup(
            tabRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRegLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(tabRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(122, 122, 122)
                .addGroup(tabRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmit)
                    .addGroup(tabRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                        .addComponent(txtLogid)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)
                        .addComponent(txtPass)
                        .addComponent(txtCnfPass)))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        tabRegLayout.setVerticalGroup(
            tabRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRegLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(tabRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLogid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtCnfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        serverpane.addTab("Registration", tabReg);

        tbarMsg.setFloatable(false);
        tbarMsg.setRollover(true);
        tbarMsg.add(lblMsg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(serverpane)
                .addContainerGap())
            .addComponent(tbarMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(serverpane, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(tbarMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStatusMouseEntered
        // TODO add your handling code here:
        this.lblMsg.setText("Current Network Status...");
    }//GEN-LAST:event_txtStatusMouseEntered

    private void txtStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStatusMouseExited
        // TODO add your handling code here:
        this.lblMsg.setText("");
    }//GEN-LAST:event_txtStatusMouseExited

    private void txtLogidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLogidActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtLogidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLogidMouseEntered
        // TODO add your handling code here:
        this.lblMsg.setText("Provide Login Id for New User...");
    }//GEN-LAST:event_txtLogidMouseEntered

    private void txtLogidMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLogidMouseExited
        // TODO add your handling code here:
        this.lblMsg.setText("");
    }//GEN-LAST:event_txtLogidMouseExited

    private void serverpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serverpaneMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_serverpaneMouseEntered

    private void txtPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMouseEntered
        // TODO add your handling code here:
         this.lblMsg.setText("Provide password for New User...");
    }//GEN-LAST:event_txtPassMouseEntered

    private void txtPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMouseExited
        this.lblMsg.setText("");
    }//GEN-LAST:event_txtPassMouseExited

    private void txtCnfPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCnfPassMouseEntered
        // TODO add your handling code here:
           this.lblMsg.setText("confirm password");
    }//GEN-LAST:event_txtCnfPassMouseEntered

    private void txtCnfPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCnfPassMouseExited
        // TODO add your handling code here:
         this.lblMsg.setText("");
    }//GEN-LAST:event_txtCnfPassMouseExited

    private void txtUserNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMouseEntered
        // TODO add your handling code here:
        this.lblMsg.setText("provide user name...");
    }//GEN-LAST:event_txtUserNameMouseEntered

    private void txtUserNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMouseExited
        // TODO add your handling code here:
         this.lblMsg.setText("");
    }//GEN-LAST:event_txtUserNameMouseExited

    private void txtEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseEntered
        // TODO add your handling code here:
         this.lblMsg.setText("provide mail id...");
    }//GEN-LAST:event_txtEmailMouseEntered

    private void txtEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseExited
        // TODO add your handling code here:
        this.lblMsg.setText("");
        
    }//GEN-LAST:event_txtEmailMouseExited

    private void txtDescMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescMouseExited
        // TODO add your handling code here:
        this.lblMsg.setText("");
    }//GEN-LAST:event_txtDescMouseExited

    private void txtDescMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescMouseEntered
        // TODO add your handling code here:
        this.lblMsg.setText("provide description...");
    }//GEN-LAST:event_txtDescMouseEntered

    private void jdisableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdisableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdisableActionPerformed

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
           // TODO add your handling code here:
                    
    }//GEN-LAST:event_btnSubmitMouseClicked

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(this.txtLogid.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Login Id Not Provided!!!","Registration",JOptionPane.ERROR_MESSAGE);
                return;
           
           }
                if(new String(this.txtPass.getPassword()).equals("")){
                JOptionPane.showMessageDialog(this,"Password Not Provided!!!","Registration",JOptionPane.ERROR_MESSAGE);
                return;
                       
           }
                 if(new String(this.txtCnfPass.getPassword()).equals("")){
                JOptionPane.showMessageDialog(this,"Password Not provided!!!","Registration",JOptionPane.ERROR_MESSAGE);
                return;
           
           }
                if (!(new String(this.txtCnfPass.getPassword())).equals(new String(txtPass.getPassword()))){
                JOptionPane.showMessageDialog(this,"Password Not matched!!!","Registration",JOptionPane.ERROR_MESSAGE);
                return;
           
           }
                 
                  if(this.txtUserName.getText().equals("")){
                JOptionPane.showMessageDialog(this,"user name Not Provided!!!","Registration",JOptionPane.ERROR_MESSAGE);
                return;
                       
           }
                   
                  if(this.txtEmail.getText().equals("")){
                JOptionPane.showMessageDialog(this,"email id Not Provided!!!","Registration",JOptionPane.ERROR_MESSAGE);
                return;
                       
           }
                  Calendar calendar=Calendar.getInstance();
                  int y=calendar.get(Calendar.YEAR);
                  int m=calendar.get(Calendar.MONTH);
                  int d=calendar.get(Calendar.DATE);
                  
        String query="insert into user_master set " +
                     "LOGIN_ID='" + this.txtLogid.getText() + "'," +
                     "PASSWORD='" + new String(this.txtPass.getPassword()) + "'," +
                     "USER_NAME='" + this.txtUserName.getText() + "'," +
                     "EMAIL_ID='" + this.txtEmail.getText() + "'," +
                     "DESCRIPTION='" + this.txtDesc.getText() + "'," +
                     "STATUS=" + "1" + "," +
                     "ADDED_ON='" + y+"/"+m+"/"+d + "'";
       try{ 
        int n=res.ConnectionFactory.getInstance().setData(query);
            if(n>0)
                JOptionPane.showMessageDialog(this, "User registered Successfully...","Registration",JOptionPane.INFORMATION_MESSAGE);
         DefaultTableModel tmodel=(DefaultTableModel)this.tblUsers.getModel();
        Vector<String> rowData=new Vector<String>();
        rowData.add(this.txtLogid.getText());
        rowData.add(this.txtUserName.getText());
        rowData.add( y+"/"+m+"/"+d);
        
         rowData.add("Active");
        
        tmodel.addRow(rowData);
        tmodel.fireTableDataChanged();   
        String msg="Hello " + this.txtUserName.getText();
        msg = msg + "\n" + "Your Login Id and Password for accesing Chat Forum are as follows :";
        msg = msg + "\n" + "Login Id: " + this.txtLogid.getText();
        msg = msg + "\n" + "Password: " + new String(this.txtPass.getPassword());
        msg = msg + "\n\n" + "Happy Chatting...";
        msg = msg + "\n" + "Chat Forum Team";
        
        if(Mailer.send("poonamagarwal0071@gmail.com","jaiganesh9@",this.txtEmail.getText(),"Chat Forum: UserName/Password",msg))
           JOptionPane.showMessageDialog(this,"Mail send Successfully...","Mailer",JOptionPane.INFORMATION_MESSAGE);
        else
           JOptionPane.showMessageDialog(this,"Could not send mail!!!","Mailer",JOptionPane.ERROR_MESSAGE); 
        //reset the entry form 
        this.txtLogid.setText("");
        this.txtPass.setText("");
        this.txtCnfPass.setText("");
        this.txtUserName.setText("");
        this.txtEmail.setText("");
        this.txtDesc.setText("");
        
        
        
       }catch(Exception e){
           e.printStackTrace();
           JOptionPane.showMessageDialog(this, "Could not register!!! \n" + e,"Registration",JOptionPane.ERROR_MESSAGE);
           
       }

    }//GEN-LAST:event_btnSubmitActionPerformed
         // TODO add your handling code here:

    public void setNetworkStatus(String status){
        this.txtStatus.append("\n" + status);
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ServerWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ServerWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ServerWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ServerWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ServerWin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jdisable;
    private javax.swing.JButton jenable;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JTabbedPane serverpane;
    private javax.swing.JPanel tabReg;
    private javax.swing.JPanel tabStatus;
    private javax.swing.JPanel tabUsers;
    private javax.swing.JToolBar tbarMsg;
    private javax.swing.JTable tblUsers;
    private javax.swing.JPasswordField txtCnfPass;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogid;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextArea txtStatus;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
