/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientsapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.WindowConstants;
import javax.swing.event.ListDataListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import res.ChatDetails;
import res.ClientDetails;
import res.Group;

/**
 *
 * @author define
 */
public class ChatWindow extends javax.swing.JFrame {

    /**
     * 
     * 
     * Creates new form ChatWindow
     */
    int index;
    int index1;
    
    public ChatWindow() {
        initComponents();
       // this.pnlCreate.setVisible(false);
        this.jTabbedPane1.setEnabledAt(0, false);
        this.jTabbedPane1.setEnabledAt(1, false);
        this.jTabbedPane1.setEnabledAt(2, false);
        this.jTabbedPane1.setSelectedIndex(3);
        //this.pnlSettings.setVisible(false);
        this.btnExit.setVisible(false);
        //this.btnSetting.setVisible(false);
        this.lblGrpId.setVisible(false);
        //this.btnaccept.setVisible(false);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        for(int i=0;i<res.CommRes.groups.size();i++)
            this.addNewGroup(res.CommRes.groups.get(i));
    }
    
    public void enableTab()
    {
        this.jTabbedPane1.setEnabledAt(1, true); 
    }
      public void visibility()
      {
      this.btnSendReq.setVisible(true);
      }
    public void changeAdmin(res.Group group)
    {
         this.txtAdmin.setText(group.admin.name);
    }
    public void enable(){
        this.jTabbedPane1.setEnabledAt(0, false);
        this.jTabbedPane1.setEnabledAt(1, false);
        this.jTabbedPane1.setEnabledAt(2, false);
        this.jTabbedPane1.setEnabledAt(3, true); 
        DefaultTableModel tmodel=(DefaultTableModel)this.tblGroups.getModel();
        tmodel.setRowCount(0);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        lblMesg = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlChat = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMesg = new javax.swing.JTextArea();
        btnAttach = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblMsg = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();
        pnlSettings = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstGrpMembers = new javax.swing.JList<>();
        lblMember = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstRequest = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        btnaccept = new javax.swing.JButton();
        btnNewAdmin = new javax.swing.JButton();
        pnlDetails = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblCreate = new javax.swing.JLabel();
        txtAdmin = new javax.swing.JTextField();
        txtCreateOn = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstActive = new javax.swing.JList();
        lblGroup = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtDescGroup = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtGroupTitle = new javax.swing.JTextField();
        btnSendReq = new javax.swing.JButton();
        lblGrpId = new javax.swing.JLabel();
        pnlCreate = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtGrpName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblHeading = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtGrpDesc = new javax.swing.JTextArea();
        btnCreateSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGroups = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        lblMesg.setText("Welcome");
        jToolBar1.add(lblMesg);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        txtMesg.setColumns(20);
        txtMesg.setRows(5);
        jScrollPane4.setViewportView(txtMesg);

        btnAttach.setText("Attach");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });

        btnSend.setText("send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        tblMsg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMsg.setGridColor(new java.awt.Color(255, 255, 255));
        tblMsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMsgMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblMsg);
        if (tblMsg.getColumnModel().getColumnCount() > 0) {
            tblMsg.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblMsg.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChatLayout = new javax.swing.GroupLayout(pnlChat);
        pnlChat.setLayout(pnlChatLayout);
        pnlChatLayout.setHorizontalGroup(
            pnlChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlChatLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlChatLayout.createSequentialGroup()
                        .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING)
        );
        pnlChatLayout.setVerticalGroup(
            pnlChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChatLayout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChatLayout.createSequentialGroup()
                        .addComponent(btnAttach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChatLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Chat", pnlChat);

        lstGrpMembers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstGrpMembers);

        lblMember.setText("Members");

        lstRequest.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstRequestMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(lstRequest);

        jLabel3.setText(" Request");

        btnaccept.setText("Accept");
        btnaccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacceptActionPerformed(evt);
            }
        });

        btnNewAdmin.setText("set as new admin");
        btnNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSettingsLayout = new javax.swing.GroupLayout(pnlSettings);
        pnlSettings.setLayout(pnlSettingsLayout);
        pnlSettingsLayout.setHorizontalGroup(
            pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettingsLayout.createSequentialGroup()
                .addGroup(pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSettingsLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(lblMember, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSettingsLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNewAdmin)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addGroup(pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSettingsLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSettingsLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSettingsLayout.createSequentialGroup()
                        .addComponent(btnaccept)
                        .addGap(122, 122, 122))))
        );
        pnlSettingsLayout.setVerticalGroup(
            pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettingsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnaccept)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(pnlSettingsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblMember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewAdmin)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Settings", pnlSettings);

        jLabel1.setText("Members");

        lblAdmin.setText("ADMIN : ");

        lblCreate.setText("CREATED ON :");

        txtCreateOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateOnActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstActive);

        jLabel5.setText("DESCRIPTION:");

        txtDescGroup.setColumns(20);
        txtDescGroup.setRows(5);
        jScrollPane7.setViewportView(txtDescGroup);

        jLabel6.setText("TITLE :");

        btnSendReq.setText("Send Joining Request");
        btnSendReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendReqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDetailsLayout = new javax.swing.GroupLayout(pnlDetails);
        pnlDetails.setLayout(pnlDetailsLayout);
        pnlDetailsLayout.setHorizontalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailsLayout.createSequentialGroup()
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1))
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDetailsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(lblAdmin)))))
                            .addGroup(pnlDetailsLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(lblGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAdmin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCreateOn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(txtGroupTitle)
                            .addGroup(pnlDetailsLayout.createSequentialGroup()
                                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGrpId)
                                    .addComponent(btnSendReq))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(77, 77, 77))
        );
        pnlDetailsLayout.setVerticalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGroup)
                    .addComponent(lblGrpId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetailsLayout.createSequentialGroup()
                        .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdmin))
                        .addGap(39, 39, 39)
                        .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtGroupTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(46, 46, 46)
                        .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCreateOn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreate))
                        .addGap(18, 18, 18)
                        .addComponent(btnSendReq)
                        .addGap(36, 36, 36))))
        );

        jTabbedPane1.addTab("Details", pnlDetails);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Group Title");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Group Description");

        lblHeading.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblHeading.setText("Provide New Group Details");

        txtGrpDesc.setColumns(20);
        txtGrpDesc.setRows(5);
        jScrollPane6.setViewportView(txtGrpDesc);

        btnCreateSubmit.setText("Create");
        btnCreateSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSubmitActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCreateLayout = new javax.swing.GroupLayout(pnlCreate);
        pnlCreate.setLayout(pnlCreateLayout);
        pnlCreateLayout.setHorizontalGroup(
            pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateLayout.createSequentialGroup()
                .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCreateLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(148, 148, 148)
                        .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGrpName, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCreateLayout.createSequentialGroup()
                                .addComponent(btnCreateSubmit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancel))))
                    .addGroup(pnlCreateLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(lblHeading)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        pnlCreateLayout.setVerticalGroup(
            pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblHeading)
                .addGap(47, 47, 47)
                .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGrpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateSubmit)
                    .addComponent(btnCancel))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create", pnlCreate);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        tblGroups.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Groups"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGroups.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGroupsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGroups);
        if (tblGroups.getColumnModel().getColumnCount() > 0) {
            tblGroups.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCreateOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateOnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreateOnActionPerformed

    private void btnNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAdminActionPerformed
        // TODO add your handling code here:
        int index=this.lstGrpMembers.getSelectedIndex();
        if(index < 0){
            JOptionPane.showMessageDialog(this, "No user Selected!!!","Request",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
     try{
         this.jTabbedPane1.setEnabledAt(1, false);
     ObjectOutputStream out=new ObjectOutputStream(res.CommRes.client.getOutputStream());    
         out.writeObject("NewAdmin");
         out.writeObject(this.lblGrpId.getText());   
         out.writeObject(index);
         
          } 
     catch(Exception e){
     
     System.out.println(e);
     
     }  
    }//GEN-LAST:event_btnNewAdminActionPerformed

    private void btnacceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacceptActionPerformed
        // TODO add your handling code here:
        int index=this.lstRequest.getSelectedIndex();
        if(index < 0){
            //message
            JOptionPane.showMessageDialog(this, "No user Selected!!!","Request",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
     try{
     ObjectOutputStream out=new ObjectOutputStream(res.CommRes.client.getOutputStream());    
         out.writeObject("accept");
         out.writeObject(this.lblGrpId.getText());   
         out.writeObject(index);
//         res.Group group=res.CommRes.groups.get(index);
//         ClientDetails details=new ClientDetails();
//               details.id=group.requests.get(index1).id;
//                             details.name=group.requests.get(index1).name;
//                               details.client=group.requests.get(index1).client;
//                 group.active.add(details);
//                           group.requests.remove(index1);
//                this.lstRequest.removeAll();
//                 Vector<String> listData=new Vector<String>();
//                for(int i=0;i<group.requests.size();i++)
//                {
//                     ClientDetails details1=group.requests.get(i);
//                    listData.add(details1.name);
//                }
//                    
//                    this.lstRequest.setListData(listData);
//            this.lstGrpMembers.removeAll();
//                 Vector<String> listData1=new Vector<String>();
//                for(int i=0;i<group.active.size();i++)
//                {
//                     ClientDetails details2=group.active.get(i);
//                    listData1.add(details2.name);
//                }
//                    
//                    this.lstGrpMembers.setListData(listData);
//                    this.lstActive.removeAll();
//                 Vector<String> listData2=new Vector<String>();
//                for(int i=0;i<group.active.size();i++)
//                {
//                     ClientDetails details2=group.active.get(i);
//                    listData2.add(details2.name);
//                }
//                    
//                    this.lstActive.setListData(listData);
         
     } 
     catch(Exception e){
     
     System.out.println(e);
     
     }  
        
        
        
    }//GEN-LAST:event_btnacceptActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.pnlCreate.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCreateSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSubmitActionPerformed
        // TODO add your handling code here:
        
        //perform Validation checks..
        if(this.txtGrpName.getText().equals(""))
        {
             JOptionPane.showMessageDialog(this,"Provide Group Name","Creating Group",JOptionPane.ERROR_MESSAGE);
                return;
        }
        try{
            ObjectOutputStream out=new ObjectOutputStream(res.CommRes.client.getOutputStream());
            out.writeObject("NewGroup");
            out.writeObject(this.txtGrpName.getText());
            out.writeObject(this.txtGrpDesc.getText());
            JOptionPane.showMessageDialog(this, "New group created successfully!!!","Group",JOptionPane.INFORMATION_MESSAGE);
            this.txtGrpName.setText("");
            this.txtGrpDesc.setText("");
            this.pnlCreate.setVisible(false);
                    
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_btnCreateSubmitActionPerformed

    private void tblGroupsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGroupsMouseClicked
        // TODO add your handling code here:
        if(this.tblGroups.getSelectedRowCount() > 0){
            this.jTabbedPane1.setEnabledAt(0, false);
            this.jTabbedPane1.setEnabledAt(1, false);
            this.jTabbedPane1.setEnabledAt(2, true);
            int index=this.tblGroups.getSelectedRow();
            res.Group group=res.CommRes.groups.get(index);
            this.lblGrpId.setText(index + "");
            this.lstActive.removeAll();
            this.lstGrpMembers.removeAll();
            boolean member=false;
            Vector<String> listData=new Vector<String>();
            this.btnSendReq.setVisible(true);
            for(int i=0;i<group.active.size();i++){
                if(group.active.get(i).id.equals(res.CommRes.id)){
                    member=true;
                    this.jTabbedPane1.setEnabledAt(0, true);
                    this.jTabbedPane1.setSelectedIndex(0);
                    this.btnExit.setVisible(true);
                    this.btnSendReq.setVisible(false);
                    DefaultTableModel tmodel=(DefaultTableModel)this.tblMsg.getModel();
                    tmodel.setRowCount(0);
                    for(int j=0;j<group.chat.size();j++){
                        this.updateChatTable(group.chat.get(j));
                    }
                    
                }
                listData.add(group.active.get(i).name);
                this.txtAdmin.setText(group.admin.name);
                this.txtGroupTitle.setText(group.title);
                this.txtDescGroup.setText(group.desc);
                this.txtCreateOn.setText(group.created_on);
            }
            
            this.lstActive.setListData(listData);
            this.lstGrpMembers.setListData(listData);
            if(group.admin.id.equals(res.CommRes.id)){
                this.jTabbedPane1.setEnabledAt(1,true);
                this.lstRequest.removeAll();
                listData=new Vector<String>();
                for(int i=0;i<group.requests.size();i++){
                    ClientDetails details=group.requests.get(i);
                    listData.add(details.name);
                    
                }
                this.lstRequest.setListData(listData);
            }
            
            if(!member)
                this.jTabbedPane1.setSelectedIndex(2);
            
        }
        
    }//GEN-LAST:event_tblGroupsMouseClicked

    private void btnSendReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendReqActionPerformed
        // TODO add your handling code here:
        try {
            ObjectOutputStream out=new ObjectOutputStream(res.CommRes.client.getOutputStream());
            out.writeObject("JoinRequest");
            out.writeObject(this.lblGrpId.getText());
            JOptionPane.showMessageDialog(this, "Joining request send to admin Successfully...","Group Join",JOptionPane.INFORMATION_MESSAGE);
           this.btnSendReq.setVisible(false); 
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSendReqActionPerformed

    private void lstRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstRequestMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_lstRequestMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog (this, "Are you sure?","EXIT GROUP", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) { 
            boolean grp_member=false;
            boolean admin=false;
       
            int index=Integer.parseInt(this.lblGrpId.getText());
            res.Group group=res.CommRes.groups.get(index);
            if(group.admin.id.equals(res.CommRes.id))
                 admin=true;  
            else{
                for(int i=0;i<group.active.size();i++){
                    if(group.active.get(i).id.equals(res.CommRes.id)){
                            grp_member=true;  
                            break;
                    }
                }
            }
             
            if(admin){// If admin : delete group
                try{
                    ObjectOutputStream out=new ObjectOutputStream(res.CommRes.client.getOutputStream());
                    out.writeObject("GroupDel");
                    out.writeObject(index+"");
                    JOptionPane.showMessageDialog(this, "Group deleted successfully!!!","Group",JOptionPane.INFORMATION_MESSAGE);
                }catch(Exception ex){
            
                }  
            }
             
            if(grp_member){// If group member : delete member from active array list
                this.jTabbedPane1.setEnabledAt(0, false);
                this.jTabbedPane1.setSelectedIndex(2);
                try{
                    ObjectOutputStream out=new ObjectOutputStream(res.CommRes.client.getOutputStream());
                    out.writeObject("GroupExit");
                    out.writeObject(index+"");
                    JOptionPane.showMessageDialog(this, "Exited from group successfully!!!","Group",JOptionPane.INFORMATION_MESSAGE);
                }catch(Exception ex){
            
                }  
            }
             
        }                                       
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        if(this.txtMesg.getText().equals("")){
            JOptionPane.showMessageDialog(this,"No Message!!!","Chat Message",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            ObjectOutputStream out=new ObjectOutputStream(res.CommRes.client.getOutputStream());
            out.writeObject("ChatMesg");
            out.writeObject(this.txtMesg.getText());
            out.writeObject(this.lblGrpId.getText());
            this.txtMesg.setText("");
        }catch(Exception ex){
            
        }
        
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(this);
        File file=chooser.getSelectedFile();
        if(file!=null){
            try {
                FileInputStream in=new FileInputStream(file);
                byte barr[]=new byte[(int)file.length()];
                in.read(barr);
                in.close();
                String fname=file.getName();
                ObjectOutputStream out=new ObjectOutputStream(res.CommRes.client.getOutputStream());
                out.writeObject("ChatMesgAttach");
                out.writeObject(barr);
                out.writeObject(fname);
                out.writeObject(this.lblGrpId.getText());
                
                
            } catch (Exception e) {
            }
            
            
        }
        
        
    }//GEN-LAST:event_btnAttachActionPerformed

    private void tblMsgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMsgMouseClicked
        // TODO add your handling code here:
        if(this.tblMsg.getSelectedRowCount() > 0){
            int row=this.tblMsg.getSelectedRow();
            int grpId=Integer.parseInt(this.lblGrpId.getText());
            Group group=res.CommRes.groups.get(grpId);
            if(group.chat.get(row).type.equals("media")){
                JFileChooser chooser=new JFileChooser();
                chooser.showSaveDialog(this);
                File file=chooser.getSelectedFile();
                if(file!=null){
                    try {
                        ObjectOutputStream out=new ObjectOutputStream(res.CommRes.client.getOutputStream());
                        out.writeObject("ChatData");
                        out.writeObject(grpId + "");
                        out.writeObject(row + "");
                        out.writeObject(file.getPath());
                        
                    } catch (Exception e) {
                    }
                    
                    
                }
            }
            
        }
    }//GEN-LAST:event_tblMsgMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Are you sure???","Logout",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            try {
                ObjectOutputStream out=new ObjectOutputStream(res.CommRes.client.getOutputStream());
                out.writeObject("Logout");
                this.dispose();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreateSubmit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNewAdmin;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSendReq;
    private javax.swing.JButton btnaccept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblGroup;
    private javax.swing.JLabel lblGrpId;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblMember;
    private javax.swing.JLabel lblMesg;
    private javax.swing.JList lstActive;
    private javax.swing.JList<String> lstGrpMembers;
    private javax.swing.JList<String> lstRequest;
    private javax.swing.JPanel pnlChat;
    private javax.swing.JPanel pnlCreate;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlSettings;
    private javax.swing.JTable tblGroups;
    private javax.swing.JTable tblMsg;
    private javax.swing.JTextField txtAdmin;
    private javax.swing.JTextField txtCreateOn;
    private javax.swing.JTextArea txtDescGroup;
    private javax.swing.JTextField txtGroupTitle;
    private javax.swing.JTextArea txtGrpDesc;
    private javax.swing.JTextField txtGrpName;
    private javax.swing.JTextArea txtMesg;
    // End of variables declaration//GEN-END:variables

    void addNewGroup(Group group) {
        DefaultTableModel tmodel=(DefaultTableModel)this.tblGroups.getModel();
        Vector<String> rowData=new Vector<String>();
        rowData.add(group.title);
        tmodel.addRow(rowData);
        tmodel.fireTableDataChanged();
        
        //int row=tmodel.getRowCount();
        //tmodel.setValueAt(group.title, 0, 0);
    }

    int getGroupId() {
        String txt=this.lblGrpId.getText();
        if(txt.equals(""))
            return -1;
        else
           return Integer.parseInt(txt);
    }

    void setRequestList(Vector listData) {
        this.lstRequest.setListData(listData);
    }

    void setActiveList(Vector listData) {
        this.lstActive.setListData(listData);
        this.lstGrpMembers.setListData(listData);
    }

    void updateChatTable(ChatDetails cdetails) {
        DefaultTableModel tmodel=(DefaultTableModel)this.tblMsg.getModel();
        Vector<String> rowData=new Vector<String>();
        rowData.add(cdetails.name + "\n(" + cdetails.sent_on + ")");
        rowData.add(cdetails.content);
        tmodel.addRow(rowData);
        tmodel.fireTableDataChanged();
    }

    void setGroupEmpty() {
        DefaultTableModel tmodel=(DefaultTableModel)this.tblMsg.getModel();
        tmodel.setRowCount(0);
    }
        
}
